### ISSUE TITLE
[REQUEST]: Test path

### ISSUE THREAD

**Issue by KenLucke** [edekeijzer/OctoPrint-WebDavBackup#6]
Please add the ability to test the path/verify permissions.  Perhaps even allow navigation to the folder once the base URL  has been entered and tested.

**Comment by edekeijzer** [comment]
Nice one, I'll look into it. Can't promise anything since this requires some knowledge of the Octoprint UI framework.

**Comment by fiaskogaul** [comment]
I would also favor that. Or is there a way to debug if the backups won't get uploaded?

Thanks and Regards

**Comment by beshur** [comment]
Hi! Also interested in debugging. Doesn't work for me on a local QNAP NAS (verified web dav creds using mac finder)

**Comment by edekeijzer** [comment]
So, nobody was expecting this anymore, but after 2.5 years there is some actual progress! In the _test_connection_ branch I have created a mock-up for the connection test. It will now randomly succeed or fail, actually testing the connection isn't even the hardest part but I'll have to restructure the plugin a bit because I'd have to copy half of the existing code otherwise.
Install from [this URL](https://github.com/edekeijzer/OctoPrint-WebDavBackup/archive/refs/heads/test_connection.zip) for a preview, no existing functionality has been altered.

**Comment by edekeijzer** [comment]
It's there! Thought this was a good reason to release as version 1.0.
Please mind that it will test against the currently _saved_ credentials, so save first and then test. I'll look into using the current values of the fields for the test.

**Comment by beshur** [comment]
Ok, thanks!
Now it says:
Test failed HTTP error encountered: 409 Conflict

What next?)
Time is okay on Raspberry and NAS.

**Comment by beshur** [comment]
Okay, I updated the server to use IP (instead of hostname) and created the folder for backups manually, but now the test spins forever (minutes). Though I hear the NAS drives spinning when the test is initiated.

But now the backup actually works :)
